### ISSUE TITLE
How can this happen?

### ISSUE THREAD

**Issue by Junkya4** [brandonlw/Psychson#199]
Hello there,
As noted in the EmbedPayload program, it finds the bytes 0x12345678. Now seeing the bin image of the firmware file, this pattern is written after the command 0x22, which in 8051 is Return from function. My doubt is, how is the embedded payload in the firmware after the return statement, executed?

**Comment by brandonlw** [comment]
The return statement you're seeing is likely from a subroutine. That or
another subroutine is accessing the address after the return statement in
order to read the payload and return it over USB in the form of keystrokes.

There's nothing suspicious about referencing data after code in 8051.

**Comment by Junkya4** [comment]
Thanks for the reply in short time @brandonlw,
It's actually the end of the subroutine as it may be noticed. After the subroutine return, no function is trying to access the code beneath(its full of zeros).
Yes there's nothing wrong, but if the execution pointer never gets there, it couldn't be executed..!
So how do we say that it can definitely get executed?

**Comment by brandonlw** [comment]
You seem to think the "payload" is 8051 code -- it isn't. It's a series of
bytes that the firmware reads from and interprets as a series of
keystrokes, which it then sends back over USB in HID format.

The execution pointer is never there. It's read from as data.

**Comment by Junkya4** [comment]
Thanks again, got your point.

**Comment by brandonlw** [comment]
Rubber Ducky "payloads" are bytes that represent keys -- let's say, for
argument's sake, that 0x01 is "A", 0x02 is "B", etc. The flash drive
firmware reads a byte from the payload, interprets it as the letter "A",
then simulates the key down and key up event over USB, as a HID keyboard.

I'm not sure why you're confused over this -- it's the same thing a Rubber
Ducky's firmware is doing.

**Comment by Junkya4** [comment]
Gotcha, still am confused, how will it be able to load, the low level details of course? It's like how will it interpret it's gonna (firmware) has to transfer over usb. Still confused, how would the firmware read the bytes. Like the firmware is loaded in the drive, the payload is inside the firmware too... Who reads the payload?
P.S.:- @brandonlw thanks for staying patient and answering.

**Comment by brandonlw** [comment]
The firmware is capable of reading data embedded within itself. I don't
know what's confusing about that.

The firmware implements all high-level USB communication, including the USB
HID protocol used by keyboards and mice.
It can simulate keystrokes the exact same way a real keyboard would.


On Nov 18, 2017 9:09 AM, "Junkya4" <notifications@github.com> wrote:

Gotcha, still am confused, how will it be able to load, the low level
details of course? It's like how will it interpret it's gonna (firmware)
has to transfer over usb. Still confused, how would the firmware read the
bytes. Like the firmware is loaded in the drive, the payload is inside the
firmware too... Who reads the payload?
P.S.:- @brandonlw <https://github.com/brandonlw> thanks for staying patient
and answering.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/brandonlw/Psychson/issues/199#issuecomment-345444613>,
or mute the thread

**Comment by Junkya4** [comment]
Thank you, again.. Couldn't reply shortly. Thanks a lot.

**Comment by Junkya4** [comment]
Hello again @brandonlw, is the default firmware itself capable of reading, or do we add this to it, as we are trying this over to a SMI device, it doesn't seem to be working. We Upload the custom firmware, with the simple payload at multiple locations, the ISP checksum also changes but the payload isn't working.. Any ideas why not?

**Comment by brandonlw** [comment]
This obviously doesn't work on an SMI device. I don't know why you'd think
it would. Their firmware is completely different.

Your line of questioning suggests this is beyond your capabilities. I don't
think I can be of any more help.


On Dec 2, 2017 2:06 PM, "Junkya4" <notifications@github.com> wrote:

Hello again @brandonlw <https://github.com/brandonlw>, is the default
firmware itself capable of reading, or do we add this to it, as we are
trying this over to a SMI device, it doesn't seem to be working. We Upload
the custom firmware, in the file at multiple locations, the ISP checksum
also changes but the payload isn't working.. Any ideas why not?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/brandonlw/Psychson/issues/199#issuecomment-348712840>,
or mute the thread

**Comment by Junkya4** [comment]
In response,
I think it is, and to extend them, I'm asking ur help with these questions... To be clear, SMI tool does send arbitrary commands to the chip. @brandonlw, I still can't understand which commands are run in the firmware to read itself,. AFAIK, there doesn't exist any software in which it has the code to read itself. Thanks for bearing.

**Comment by brandonlw** [comment]
Now you're talking about developing firmware for a different controller
(SMI instead of Phison), which is beyond the scope of this repository.

With Phison, my earlier responses had to do with the 8051 code reading from
the running copy in RAM. Official firmware is much larger than the small
chunk running from RAM, and it has to read into RAM and execute the
sections it needs as it needs it. If you want to know how to read the
entire firmware from the NAND chip, I recommend you disassemble it and
study it.


On Dec 5, 2017 11:44 PM, "Junkya4" <notifications@github.com> wrote:

In response,
I think it is, and to extend them, I'm asking ur help with these
questions... To be clear, SMI tool does send arbitrary commands to the
chip. @brandonlw <https://github.com/brandonlw>, I still can't understand
which commands are run in the firmware to read itself,. AFAIK, there
doesn't exist any software in which it has the code to read itself. Thanks
for bearing.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/brandonlw/Psychson/issues/199#issuecomment-349531876>,
or mute the thread
