### ISSUE TITLE
Firmware update hangs / bricks device: what to do?

### ISSUE THREAD

**Issue by jeroen-80** [brandonlw/Psychson#42]
Hi,

I tried to flash a USB thumb drive with a 2251-03Q controller:

C:\tmp\Psychson-master>tools\DriveCom.exe /drive=D /action
=SendFirmware /burner=BN03V104M.BIN /firmware=fw.bin
Action specified: SendFirmware
Gathering information...
Reported chip type: 2303
Reported chip ID: 98-DE-98-92-72-D7
Reported firmware version: 1.10.53
Mode: Firmware
Switching to boot mode...
Rebooting...
Sending firmware...
Executing...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0079
   at DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byte
[] data, Int32 bytesExpected) in c:\Users\bofh\Desktop\BadUSB\Psychson-master\Dr
iveCom\DriveCom\PhisonDevice.cs:line 366
   at DriveCom.Startup._RunFirmware(String fileName) in c:\Users\bofh\Desktop\Ba
dUSB\Psychson-master\DriveCom\DriveCom\Startup.cs:line 443
   at DriveCom.Startup.Main(String[] args) in c:\Users\bofh\Desktop\BadUSB\Psych
son-master\DriveCom\DriveCom\Startup.cs:line 115

The drive seems to be bricked: it doesn't show up anymore and is not detectable in any way I'm aware of (drive letter / low level USB monitor etc.).

Do you have any clues about what went wrong and if it's possible to unbrick the device? Thanks!

Cheers,

Jeroen

**Comment by jhuber-de** [comment]
You can try to short the data pins.
https://github.com/adamcaudill/Psychson/wiki/Executing-From-Boot-ROM#entering-boot-mode-from-hardware

**Comment by jeroen-80** [comment]
Shortening the pins doesn't seem to change anything but perhaps I did something wrong (unfortunately the drive doesn't have a LED to check the status). For sure no drive letter pops up and I cannot detect any other activity. Can you please tell me what to do after shortening the pins and connecting the drive?  What tools can I use to check / reflash the drive? If someone can provide me with a console output of a successful recovery that would be very useful. 

The drive is a no-name unknown make drive btw. Opening the case shows that the controller is a 2251-03Q.

Thanks!

**Comment by jhuber-de** [comment]
Windows has a setting that hides drive letters for empty or ejected drives, which is what the drive will be when custom firmware is flashed to it. You might try changing that setting in Folder Options in Control Panel to see if you can get the drive letter to appear. 
Also windows recognize the drive if it is in bootmode just like a new drive and trys to install drivers you will see if the drive if it is in bootmode with an drive letter (at least that what happens with my usb-drive) so you will get feedback if you are in bootmode without LED. 
To check the drive use: DriveCom.exe /drive=L /action=GetInfo (where L = the letter of the usb-stick).
Restore the old Firmware should work like flashing a custom one just select your backed up fw instead of the manipulated fw

**Comment by Mo-Ko** [comment]
Short the pins via knife or common pin. Inject the USB and as soon as you hear the Windows sound for detecting hardware unshort the pins. After this you might not see the drive but you can check it via DriveCom.exe /drive=<Drive letter which normally assign to your USB > /action=GetInfo

**Comment by gfleck** [comment]
Hello.

I do the steps:

C:\BadUSB\psychson_r1\tools>DriveCom.exe /drive=F /action=SetBootMode
Action specified: SetBootMode

The Led is always on. I don't short the pins yet because can't open the drive case.

Next:

C:\BadUSB\psychson_r1\tools>DriveCom.exe /drive=F /action=GetInfo
Action specified: GetInfo
Gathering information...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 048F
   em DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byte[] data, Int32 bytesExpected) na c:\Users\Brandon\
Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:linha 365
   em DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Int32 bytesExpected) na c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\D
riveCom\PhisonDevice.cs:linha 295
   em DriveCom.PhisonDevice.RequestVendorInfo() na c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:l
inha 140
   em DriveCom.PhisonDevice.GetChipType() na c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:linha 1
70
   em DriveCom.Startup._GetInfo() na c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\Startup.cs:linha 384
   em DriveCom.Startup.Main(String[] args) na c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\Startup.cs:linha 104

Anyone know how help?

**Comment by grince** [comment]
Hi, 
I have a similar symptom than Petr4; I have some Patriot Supersonic Xpress 16GB-Sticks with the following Information:

C:\Psychson\Psychson-r1>tools\DriveCom.exe /drive=I /action=GetInfo
Action specified: GetInfo
Gathering information...
Reported chip type: 2303
Reported chip ID:  aa-bb-cc-dd-ee-ff
Reported firmware version: 1.10.53
Mode: Firmware

After installing the RubberDucky-Payload, the stick stops being a flash drive. It does execute the payload (in my case, a Hello World in a notepad), but neither a "GetInfo" nor a "DumpFirmware" nor a "SendFirmware" works:

C:\Psychson\Psychson-r1>tools\DriveCom.exe /drive=I /action=GetInfo
Action specified: GetInfo
Gathering information...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0079
   bei DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byt
e[] data, Int32 bytesExpected) in c:\Users\Brandon\Documents\GitHub\PS2251-03\Dr
iveCom\DriveCom\PhisonDevice.cs:Zeile 365.
   bei DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Int32 bytesExpected) in c:\
Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile
 295.
   bei DriveCom.PhisonDevice.RequestVendorInfo() in c:\Users\Brandon\Documents\G
itHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile 140.
   bei DriveCom.PhisonDevice.GetChipType() in c:\Users\Brandon\Documents\GitHub\
PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile 170.
   bei DriveCom.Startup._GetInfo() in c:\Users\Brandon\Documents\GitHub\PS2251-0
3\DriveCom\DriveCom\Startup.cs:Zeile 384.
   bei DriveCom.Startup.Main(String[] args) in c:\Users\Brandon\Documents\GitHub
\PS2251-03\DriveCom\DriveCom\Startup.cs:Zeile 104.

I can ask for GetNumLBAs and the Number of LBAs is 0x17005C57, which should be correct.

But none of the Format-Tools I checked (MP ALL up to 3.60.0D) is able to recognize the stick anymore. And I can not put back a stock firmware or so.

I use Windows 7 64bit, I have three of the sticks, but apparently something went wrong.
If I find out how to open the casing, I can try a Hardware-Bootmode.

Do you have any idea how I can unbrick the stick? I have two more of the same batch, so I can test a little bit ;)

**Comment by Mo-Ko** [comment]
Try hardware bootmode via shorting the pin.
Btw did you test ''Hello World'' on usb 3.0 of port of PC

-------- Original message --------

**Comment by jeroen-80** [comment]
Thanks for all the responses. It seems that I was clumsy: keeping the pins shorted while inserting it to my USB port didn't work for me with a knife. In the end I used a needle to short the pins and a device similar to the one found in the original slides to power USB on and off to avoid that the needle bumps off:

![powerswitch](https://cloud.githubusercontent.com/assets/1997125/4835797/4b10c4ac-5fbb-11e4-80a9-4e3d82fbc4fe.png)

Hope this helps for other folks as well.

The USB device was bricked with a Windows 7 x64 box with USB 2.0 btw.

**Comment by grince** [comment]
@jeroen-80: I see you also have a Supersonic Express. Have you been able to pull the usb-stick out of the box without damaging the box and yes, how did you do it? Or do I have to destroy the box?

**Comment by jeroen-80** [comment]
I'm not using a Supersonic Express, as mentioned the picture is from the original presentation slides from Adam and Brandon @ http://www.slideshare.net/adam_caudill/derby-con2014presentation.

I'm using no-name sticks: I just bought a bunch and checked which are 2251-03 powered.
